name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: false # We are using HF Datasets now, so we don't want LFS

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Setup credentials
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # 2. Force push to overwrite the HF Space history
          git remote add space https://jakewatson91:$HF_TOKEN@huggingface.co/spaces/jakewatson91/sherlock || git remote set-url space https://jakewatson91:$HF_TOKEN@huggingface.co/spaces/jakewatson91/sherlock
          
          git push -f space main
